# Generated by Django 3.2.5 on 2021-12-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('username', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('register_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['register_time'],
            },
        ),
    ]
